export const PART_LIBRARY = [
  {
    id: "sticker-wen-token",
    label: "WEN Token Plate",
    text: "WEN TOKEN",
    category: "sticker",
    shape: "plate",
    art: "wen-token",
    rarity: "meme",
    snapSlot: "free",
    defaultTransform: { x: 42, y: 68, scale: 1, rotation: -5 },
    colors: ["red", "black"]
  },
  {
    id: "sticker-web3-bubble",
    label: "WEB3 Bubble",
    text: "WEB3",
    category: "sticker",
    shape: "bubble",
    art: "web3-bubble",
    rarity: "meme",
    snapSlot: "free",
    defaultTransform: { x: 28, y: 64, scale: 1, rotation: 4 },
    colors: ["white", "black"]
  },
  {
    id: "sticker-diamond-hands",
    label: "Diamond Hands Badge",
    text: "DIAMOND HANDS",
    category: "sticker",
    shape: "badge",
    art: "diamond-hands",
    rarity: "meme",
    snapSlot: "free",
    defaultTransform: { x: 63, y: 72, scale: 1, rotation: 5 },
    colors: ["silver", "cyan"]
  },
  {
    id: "sticker-hodl-coin",
    label: "HODL Coin",
    text: "HODL",
    category: "sticker",
    shape: "pill",
    art: "hodl",
    rarity: "meme",
    snapSlot: "free",
    defaultTransform: { x: 34, y: 76, scale: 1, rotation: -3 },
    colors: ["white", "gold"]
  },
  {
    id: "sticker-tape-banana",
    label: "Taped Banana Relic",
    text: "BANANA",
    category: "sticker",
    shape: "banana",
    art: "tape-banana",
    rarity: "meme",
    snapSlot: "free",
    defaultTransform: { x: 70, y: 60, scale: 1, rotation: -10 },
    colors: ["yellow", "black"]
  },
  {
    id: "sticker-when-lambo",
    label: "When Lambo Plate",
    text: "WHEN LAMBO",
    category: "sticker",
    shape: "car",
    art: "when-lambo",
    rarity: "meme",
    snapSlot: "free",
    defaultTransform: { x: 72, y: 69, scale: 1, rotation: 3 },
    colors: ["gold", "black"]
  },
  {
    id: "sticker-moon-soon",
    label: "Moon Soon Rocket",
    text: "MOON SOON",
    category: "sticker",
    shape: "rocket",
    art: "moon-soon",
    rarity: "meme",
    snapSlot: "free",
    defaultTransform: { x: 31, y: 76, scale: 1, rotation: -7 },
    colors: ["meta", "cyan"]
  },
  {
    id: "sticker-rekt-bolt",
    label: "REKT Bolt Tag",
    text: "REKT",
    category: "sticker",
    shape: "slash",
    art: "rekt-bolt",
    rarity: "meme",
    snapSlot: "free",
    defaultTransform: { x: 64, y: 66, scale: 1, rotation: -6 },
    colors: ["orange", "black"]
  },
  {
    id: "sticker-nft-chip",
    label: "NFT Chip Seal",
    text: "NFT",
    category: "sticker",
    shape: "chip",
    art: "nft-chip",
    rarity: "meme",
    snapSlot: "free",
    defaultTransform: { x: 24, y: 67, scale: 1, rotation: 5 },
    colors: ["cyan", "silver"]
  },
  {
    id: "sticker-ape-rivet",
    label: "APE Rivet Patch",
    text: "APE",
    category: "sticker",
    shape: "diamond",
    art: "ape-rivet",
    rarity: "meme",
    snapSlot: "free",
    defaultTransform: { x: 76, y: 70, scale: 1, rotation: -8 },
    colors: ["black", "gold"]
  },
  {
    id: "sticker-degen-meter",
    label: "Degen Meter",
    text: "DEGEN",
    category: "sticker",
    shape: "meter",
    art: "degen-meter",
    rarity: "meme",
    snapSlot: "free",
    defaultTransform: { x: 52, y: 82, scale: 1, rotation: -2 },
    colors: ["purple", "cyan"]
  }
];
