export const PART_LIBRARY = [
  {
    id: "sticker-wen-token",
    label: "WEN Token Plate",
    text: "WEN TOKEN",
    category: "sticker",
    shape: "plate",
    art: "wen-token",
    rarity: "meme",
    snapSlot: "free",
    defaultTransform: { x: 42, y: 68, scale: 0.78, rotation: -5 },
    colors: ["red", "gold", "black"]
  },
  {
    id: "sticker-web3-bubble",
    label: "WEB3 Bubble",
    text: "WEB3",
    category: "sticker",
    shape: "bubble",
    art: "web3-bubble",
    rarity: "meme",
    snapSlot: "free",
    defaultTransform: { x: 28, y: 64, scale: 0.78, rotation: 4 },
    colors: ["white", "cyan", "black"]
  },
  {
    id: "sticker-diamond-hands",
    label: "Diamond Hands Badge",
    text: "DIAMOND HANDS",
    category: "sticker",
    shape: "badge",
    art: "diamond-hands",
    rarity: "meme",
    snapSlot: "free",
    defaultTransform: { x: 63, y: 72, scale: 0.76, rotation: 5 },
    colors: ["silver", "cyan", "purple"]
  },
  {
    id: "sticker-hodl-coin",
    label: "HODL Coin",
    text: "HODL",
    category: "sticker",
    shape: "pill",
    art: "hodl",
    rarity: "meme",
    snapSlot: "free",
    defaultTransform: { x: 34, y: 76, scale: 0.76, rotation: -3 },
    colors: ["gold", "white", "black"]
  },
  {
    id: "sticker-tape-banana",
    label: "Taped Banana Relic",
    text: "BANANA",
    category: "sticker",
    shape: "banana",
    art: "tape-banana",
    rarity: "meme",
    snapSlot: "free",
    defaultTransform: { x: 70, y: 60, scale: 0.74, rotation: -10 },
    colors: ["yellow", "gold", "silver"]
  },
  {
    id: "sticker-when-lambo",
    label: "When Lambo Plate",
    text: "WHEN LAMBO",
    category: "sticker",
    shape: "car",
    art: "when-lambo",
    rarity: "meme",
    snapSlot: "free",
    defaultTransform: { x: 72, y: 69, scale: 0.8, rotation: 3 },
    colors: ["gold", "black", "red"]
  },
  {
    id: "sticker-moon-soon",
    label: "Moon Soon Rocket",
    text: "MOON SOON",
    category: "sticker",
    shape: "rocket",
    art: "moon-soon",
    rarity: "meme",
    snapSlot: "free",
    defaultTransform: { x: 31, y: 76, scale: 0.78, rotation: -7 },
    colors: ["meta", "cyan", "blue"]
  },
  {
    id: "sticker-rekt-bolt",
    label: "REKT Bolt Tag",
    text: "REKT",
    category: "sticker",
    shape: "slash",
    art: "rekt-bolt",
    rarity: "meme",
    snapSlot: "free",
    defaultTransform: { x: 64, y: 66, scale: 0.78, rotation: -6 },
    colors: ["orange", "red", "black"]
  },
  {
    id: "sticker-nft-chip",
    label: "NFT Chip Seal",
    text: "NFT",
    category: "sticker",
    shape: "chip",
    art: "nft-chip",
    rarity: "meme",
    snapSlot: "free",
    defaultTransform: { x: 24, y: 67, scale: 0.74, rotation: 5 },
    colors: ["cyan", "green", "silver"]
  },
  {
    id: "sticker-ape-rivet",
    label: "APE Rivet Patch",
    text: "APE",
    category: "sticker",
    shape: "diamond",
    art: "ape-rivet",
    rarity: "meme",
    snapSlot: "free",
    defaultTransform: { x: 76, y: 70, scale: 0.7, rotation: -8 },
    colors: ["black", "gold", "purple"]
  },
  {
    id: "sticker-degen-meter",
    label: "Degen Meter",
    text: "DEGEN",
    category: "sticker",
    shape: "meter",
    art: "degen-meter",
    rarity: "meme",
    snapSlot: "free",
    defaultTransform: { x: 52, y: 82, scale: 0.78, rotation: -2 },
    colors: ["purple", "cyan", "red"]
  },
  {
    id: "part-paper-hood",
    label: "Archive Paper Hood",
    text: "",
    category: "head-cover",
    group: "part",
    shape: "hood",
    art: "paper-hood",
    rarity: "wearable",
    snapSlot: "head-top",
    defaultTransform: { x: 50, y: 34, scale: 1.04, rotation: -2 },
    colors: ["tan", "gold", "black"]
  },
  {
    id: "part-horn-visor",
    label: "Solar Horn Visor",
    text: "",
    category: "headwear",
    group: "part",
    shape: "crown",
    art: "horn-visor",
    rarity: "wearable",
    snapSlot: "head-top",
    defaultTransform: { x: 50, y: 27, scale: 0.92, rotation: 1 },
    colors: ["gold", "silver", "red"]
  },
  {
    id: "part-arctic-hood",
    label: "Arctic Metal Hood",
    text: "",
    category: "head-cover",
    group: "part",
    shape: "hood",
    art: "arctic-hood",
    rarity: "wearable",
    snapSlot: "head-top",
    defaultTransform: { x: 50, y: 33, scale: 0.98, rotation: 1 },
    colors: ["blue", "silver", "black"]
  },
  {
    id: "part-ursa-hood",
    label: "Rivet Bear Hood",
    text: "",
    category: "head-cover",
    group: "part",
    shape: "hood",
    art: "ursa-hood",
    rarity: "wearable",
    snapSlot: "head-top",
    defaultTransform: { x: 50, y: 34, scale: 0.98, rotation: -1 },
    colors: ["brown", "gold", "black"]
  },
  {
    id: "part-saturn-pin",
    label: "Saturn Gear Pin",
    text: "",
    category: "head-prop",
    group: "part",
    shape: "saturn",
    art: "saturn-pin",
    rarity: "wearable",
    snapSlot: "head-top",
    defaultTransform: { x: 50, y: 22, scale: 0.86, rotation: -5 },
    colors: ["pink", "gold", "cyan"]
  },
  {
    id: "part-teddy-charm",
    label: "Teddy Gear Charm",
    text: "",
    category: "bag-charm",
    group: "part",
    shape: "charm",
    art: "teddy-gear",
    rarity: "bag part",
    snapSlot: "right-shoulder",
    defaultTransform: { x: 69, y: 62, scale: 0.78, rotation: -7 },
    colors: ["brown", "cyan", "gold"]
  },
  {
    id: "part-rocket-visor",
    label: "Rocket Eye Visor",
    text: "",
    category: "headwear",
    group: "part",
    shape: "visor",
    art: "rocket-visor",
    rarity: "wearable",
    snapSlot: "head-top",
    defaultTransform: { x: 53, y: 34, scale: 0.86, rotation: 3 },
    colors: ["red", "orange", "blue"]
  },
  {
    id: "part-gas-satchel",
    label: "Gas Satchel Plate",
    text: "GAS",
    category: "bag-part",
    group: "part",
    shape: "satchel",
    art: "gas-satchel",
    rarity: "bag part",
    snapSlot: "bag-face",
    defaultTransform: { x: 80, y: 58, scale: 0.74, rotation: -3 },
    colors: ["green", "cyan", "black"]
  }
];
